// nuxt-site/components/FloatingButtons.vue
<script setup lang="ts">
const primaryItem = {
  href: '/design-inspiration',
  icon: '/floating-icons/case.png',
  label: '設計案例',
}

const serviceItems = [
  { href: 'https://www.sakura-kitchenlife.com.tw/measuring', icon: '/floating-icons/official-quick-link-2.svg', label: '到府丈量', newTab: true },
  { href: 'https://icare.sakura.com.tw', icon: '/floating-icons/official-quick-link-3.svg', label: '線上客服', newTab: true },
]

const rail = ref<HTMLElement | null>(null)
const offset = ref(0)
const RAIL_BOTTOM_PX = 88
const reduced = useReducedMotion()
const route = useRoute()
const isFocusedMobileForm = computed(() => ['/franchising/intro', '/franchising/download', '/franchising/form', '/builders', '/about/exhibition', '/about/introduce'].includes(route.path) || route.path.startsWith('/gallery/') || route.path.startsWith('/news') || route.path.startsWith('/products'))
let frame = 0

const update = () => {
  if (!rail.value || reduced.value) { offset.value = 0; return }
  const maxScroll = Math.max(1, document.documentElement.scrollHeight - window.innerHeight)
  const progress = Math.min(1, window.scrollY / maxScroll)
  const railHeight = rail.value.offsetHeight
  const startTop = window.innerHeight - railHeight - RAIL_BOTTOM_PX
  const endTop = 112
  offset.value = Math.min(0, (endTop - startTop) * progress)
}

const requestUpdate = () => {
  cancelAnimationFrame(frame)
  frame = requestAnimationFrame(update)
}

onMounted(() => {
  update()
  window.addEventListener('scroll', requestUpdate, { passive: true })
  window.addEventListener('resize', requestUpdate)
})
onBeforeUnmount(() => {
  cancelAnimationFrame(frame)
  window.removeEventListener('scroll', requestUpdate)
  window.removeEventListener('resize', requestUpdate)
})
</script>

<template>
  <aside ref="rail" aria-label="快速服務" class="floating-buttons fixed right-0 z-[90]" :class="{ 'floating-buttons--focused-mobile-form': isFocusedMobileForm }" :style="{ bottom: `${RAIL_BOTTOM_PX}px`, transform: `translateY(${offset}px)` }">
    <a :href="primaryItem.href" :aria-label="primaryItem.label" class="relative mb-5 block h-[72px] w-[72px] bg-[#B79258] text-white sm:h-[74px] sm:w-[74px]">
      <img :src="primaryItem.icon" alt="" class="absolute top-[13px] left-1/2 h-[29px] w-[29px] -translate-x-1/2 sm:top-[14px] sm:h-[30px] sm:w-[30px]" />
      <span class="absolute inset-x-0 bottom-[11px] block whitespace-nowrap text-center font-['Noto_Sans_TC'] text-xs leading-3 sm:bottom-3">{{ primaryItem.label }}</span>
    </a>
    <div class="bg-[#737373]">
      <template v-for="(item, index) in serviceItems" :key="item.label">
        <div v-if="index" aria-hidden="true" class="h-px w-full bg-white/50" />
        <a :href="item.href" :aria-label="item.label" :target="item.newTab ? '_blank' : undefined" :rel="item.newTab ? 'noopener noreferrer' : undefined" class="block p-2">
          <img :src="item.icon" alt="" class="block w-14 sm:w-[58px]" />
        </a>
      </template>
      <button type="button" disabled title="拍立配連結待提供" class="flex h-[72px] w-[72px] items-center justify-center border-t border-white/50 font-['Noto_Sans_TC'] text-xs text-white sm:h-[74px] sm:w-[74px]">拍立配</button>
    </div>
  </aside>
</template>

<style scoped>
@media (max-width: 767px) {
  .floating-buttons--focused-mobile-form { display: none; }
}
</style>

// src/components/FloatingButtons.tsx
import React from 'react';

// 右側固定側邊欄 —— 配色/位置沿用官網 .l-quick-links 實測（金頂鈕 CIS 金 #C9AA79 + 灰群組 #737373 +
// 白分隔線、底部對齊貼右）；圖示＝使用者提供的品牌 icon（純白去背 PNG，public/floating-icons/），圖下加中文文字標籤。
// icon 非正方（案例門市 33×30、到府丈量/客服中心 38×40），故用 h-[40px] w-auto 依高度正規化、不塞正方以免變形。
// ⚠ 頂鈕『案例門市』的連結目前仍是官網『加盟』(franchising)——待提供正確 URL 再換。
const TOP = { href: 'https://www.sakura-kitchenlife.com.tw/franchising/intro', icon: '/floating-icons/case.png', label: '案例門市' };
// 灰底群組（到府丈量 / 客服中心），項間白色分隔線
const GROUP = [
  { href: 'https://www.sakura-kitchenlife.com.tw/measuring', icon: '/floating-icons/measure.png', label: '到府丈量' },
  { href: 'https://icare.sakura.com.tw', icon: '/floating-icons/service.png', label: '客服中心', external: true },
];

// 單顆按鈕內容：圖 58 + 下方白字標籤
function BtnInner({ icon, label }: { icon: string; label: string }) {
  return (
    <span className="flex flex-col items-center gap-1.5">
      <img src={icon} alt="" className="h-[40px] w-auto" />
      <span className="text-white text-[13px] leading-tight text-center whitespace-nowrap">{label}</span>
    </span>
  );
}

export function FloatingButtons() {
  return (
    <>
      {/* 桌面：原生 fixed 右側欄。 */}
      <div className="hidden lg:flex fixed inset-y-0 right-0 z-50 items-end pb-[36px] pointer-events-none">
        <div className="pointer-events-auto">
          {/* 金頂鈕（案例門市）：block p-2 mb-[20px] */}
          <a
            href={TOP.href}
            aria-label={TOP.label}
            className="block p-2 mb-[20px] bg-[#C9AA79] transition-opacity hover:opacity-90"
          >
            <BtnInner icon={TOP.icon} label={TOP.label} />
          </a>

          {/* 灰底群組：項間白色 h-px 分隔線 */}
          <div className="bg-[#737373]">
            {GROUP.map((b, i) => (
              <React.Fragment key={b.href}>
                {i > 0 && <div aria-hidden className="w-full h-px bg-white/50" />}
                <a
                  href={b.href}
                  aria-label={b.label}
                  {...(b.external ? { target: '_blank', rel: 'noopener noreferrer' } : {})}
                  className="block p-2 transition-opacity hover:opacity-90"
                >
                  <BtnInner icon={b.icon} label={b.label} />
                </a>
              </React.Fragment>
            ))}
          </div>
        </div>
      </div>

      {/* 手機／平板：底部固定列。 */}
      <div className="flex lg:hidden fixed bottom-0 left-0 right-0 z-[9999]">
        {[TOP, ...GROUP].map((b) => (
          <a
            key={b.href}
            href={b.href}
            aria-label={b.label}
            className={`flex-1 flex flex-col items-center justify-center gap-1 py-2 ${b === TOP ? 'bg-[#C9AA79]' : 'bg-[#737373]'}`}
          >
            <img src={b.icon} alt="" className="h-9 w-auto" />
            <span className="text-white text-[11px] leading-tight">{b.label}</span>
          </a>
        ))}
      </div>
    </>
  );
}
